POST http://localhost:3000/notes
Content-Type: application/json

{
        "title": "This is my new note",
        "content": "This is the content of my new note",
        "created_at": "2022-06-05",
        "created_by": 3,
        "updated_by": 0,
        "deleted": false
    }

###
POST http://localhost:3000/createUser
Content-Type: application/json

{
    "userEmail": "h",
    "userPass": "h"
}

###
POST http://localhost:3000/logIn
Content-Type: application/json

{
    "userEmail": "q",
    "userPass": "q"
}

###
GET http://localhost:3000/getCreatedBy/17

###
GET http://localhost:3000/findNotes/2

###
POST http://localhost:3000/createNote
Content-Type: application/json

    {
        "content": "This is the content of my new note",
        "created_at": "2022-06-05",
        "created_by": 5,
        "updated_by": 5,
        "deleted": false
    }

###
PUT http://localhost:3000/updateNote
Content-Type: application/json

    {
        "id": 32,
        "content": "This is the content of my updated note",
        "created_at": "2022-06-05",
        "created_by": 4, 
        "updated_by": 4,
        "deleted": 0
    }

###

PUT http://localhost:3000/deleteNote
Content-Type: application/json

    {
        "deleted": true,
        "id": 54
    }
###
GET http://localhost:3000/allNotes

###
Get http://localhost:3000/findNotes
Content-Type: application/json

    {
        "created_by": 3
    }


###

GET http://localhost:3000/getNotesWithUsers